<?php
use Migrations\AbstractSeed;

/**
 * Turbines seed.
 */
class TurbinesSeed extends AbstractSeed
{
    /**
     * Run Method.
     *
     * Write your database seeder using this method.
     *
     * More information on writing seeds is available here:
     * http://docs.phinx.org/en/latest/seeding.html
     *
     * @return void
     */
    public function run()
    {
        $data = [
            [
                'id' => '1',
                'model' => 'Town Car',
                'description' => 'risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula',
                'price' => '191.98',
                'created' => '2014-07-08 20:32:43',
                'modified' => '2017-01-19 03:03:07',
            ],
            [
                'id' => '2',
                'model' => '9-3',
                'description' => 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit',
                'price' => '131.83',
                'created' => '2014-07-11 02:41:15',
                'modified' => '2015-10-03 18:33:16',
            ],
            [
                'id' => '3',
                'model' => 'Savana',
                'description' => 'montes nascetur ridiculus mus etiam vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id',
                'price' => '176.54',
                'created' => '2014-07-11 06:26:41',
                'modified' => '2016-10-15 01:26:59',
            ],
            [
                'id' => '4',
                'model' => 'Avenger',
                'description' => 'odio porttitor id consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio',
                'price' => '120.39',
                'created' => '2015-10-21 10:55:23',
                'modified' => '2015-10-22 00:09:35',
            ],
            [
                'id' => '5',
                'model' => '626',
                'description' => 'accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus aenean fermentum donec ut',
                'price' => '143.66',
                'created' => '2014-11-12 00:31:28',
                'modified' => '2015-11-16 14:51:43',
            ],
            [
                'id' => '6',
                'model' => 'SJ',
                'description' => 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum',
                'price' => '40.73',
                'created' => '2015-04-18 05:42:11',
                'modified' => '2016-04-21 17:46:30',
            ],
            [
                'id' => '7',
                'model' => 'M3',
                'description' => 'ligula sit amet eleifend pede libero quis orci nullam molestie nibh in lectus pellentesque at',
                'price' => '186.88',
                'created' => '2015-08-04 16:04:48',
                'modified' => '2015-07-19 05:00:23',
            ],
            [
                'id' => '8',
                'model' => 'STS-V',
                'description' => 'in leo maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu',
                'price' => '140.05',
                'created' => '2015-02-19 19:01:46',
                'modified' => '2016-01-01 09:07:36',
            ],
            [
                'id' => '9',
                'model' => 'LS',
                'description' => 'tellus nulla ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit',
                'price' => '27.88',
                'created' => '2014-10-31 05:32:02',
                'modified' => '2016-04-06 06:08:15',
            ],
            [
                'id' => '10',
                'model' => 'Sierra 3500',
                'description' => 'proin interdum mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie',
                'price' => '88.83',
                'created' => '2015-12-31 03:26:15',
                'modified' => '2016-11-23 11:52:06',
            ],
            [
                'id' => '11',
                'model' => 'Supra',
                'description' => 'sed magna at nunc commodo placerat praesent blandit nam nulla integer pede justo lacinia eget tincidunt',
                'price' => '62.87',
                'created' => '2015-05-20 18:02:34',
                'modified' => '2017-02-09 21:13:30',
            ],
            [
                'id' => '12',
                'model' => 'XT',
                'description' => 'sed tincidunt eu felis fusce posuere felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet',
                'price' => '168.74',
                'created' => '2015-11-17 19:36:28',
                'modified' => '2016-11-10 06:29:20',
            ],
            [
                'id' => '13',
                'model' => 'M',
                'description' => 'at velit vivamus vel nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat eros viverra eget',
                'price' => '130.22',
                'created' => '2015-11-26 18:46:04',
                'modified' => '2016-02-13 04:48:04',
            ],
            [
                'id' => '14',
                'model' => 'Blackwood',
                'description' => 'vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum eu',
                'price' => '79.17',
                'created' => '2015-11-08 21:10:38',
                'modified' => '2016-02-19 04:57:35',
            ],
            [
                'id' => '15',
                'model' => 'X5',
                'description' => 'fusce lacus purus aliquet at feugiat non pretium quis lectus',
                'price' => '183.75',
                'created' => '2015-10-06 13:27:20',
                'modified' => '2016-10-23 22:12:24',
            ],
            [
                'id' => '16',
                'model' => 'Mirage',
                'description' => 'sapien cursus vestibulum proin eu mi nulla ac enim in',
                'price' => '153.05',
                'created' => '2014-11-07 08:02:43',
                'modified' => '2016-11-29 03:49:13',
            ],
            [
                'id' => '17',
                'model' => 'SSR',
                'description' => 'ut erat id mauris vulputate elementum nullam varius nulla facilisi cras non velit nec nisi vulputate nonummy maecenas tincidunt lacus',
                'price' => '178.09',
                'created' => '2014-08-31 02:28:20',
                'modified' => '2016-12-10 22:33:09',
            ],
            [
                'id' => '18',
                'model' => 'F250',
                'description' => 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus',
                'price' => '116.79',
                'created' => '2015-04-22 09:18:54',
                'modified' => '2016-04-07 08:43:27',
            ],
            [
                'id' => '19',
                'model' => 'VehiCROSS',
                'description' => 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum',
                'price' => '154.72',
                'created' => '2015-06-08 04:48:33',
                'modified' => '2016-10-13 02:41:39',
            ],
            [
                'id' => '20',
                'model' => 'Eurovan',
                'description' => 'rhoncus aliquet pulvinar sed nisl nunc rhoncus dui vel sem sed sagittis nam congue risus semper porta volutpat quam pede',
                'price' => '191.27',
                'created' => '2014-12-21 21:26:17',
                'modified' => '2015-12-11 12:00:48',
            ],
            [
                'id' => '21',
                'model' => 'Viper',
                'description' => 'platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem',
                'price' => '88.85',
                'created' => '2015-07-30 16:22:45',
                'modified' => '2015-10-27 22:59:24',
            ],
            [
                'id' => '22',
                'model' => 'Cordia',
                'description' => 'consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim blandit mi in',
                'price' => '168.91',
                'created' => '2015-05-07 13:15:13',
                'modified' => '2016-09-06 20:14:37',
            ],
            [
                'id' => '23',
                'model' => 'Starion',
                'description' => 'a odio in hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque',
                'price' => '46.00',
                'created' => '2015-01-05 02:55:09',
                'modified' => '2016-10-04 14:01:32',
            ],
            [
                'id' => '24',
                'model' => 'Trooper',
                'description' => 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non',
                'price' => '56.29',
                'created' => '2014-12-10 13:29:42',
                'modified' => '2016-02-06 03:50:49',
            ],
            [
                'id' => '25',
                'model' => 'B-Series',
                'description' => 'tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed magna at nunc',
                'price' => '155.46',
                'created' => '2014-12-22 12:59:22',
                'modified' => '2016-12-15 13:25:08',
            ],
            [
                'id' => '26',
                'model' => 'XT',
                'description' => 'in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat varius integer ac leo pellentesque ultrices mattis',
                'price' => '78.31',
                'created' => '2015-11-08 20:13:06',
                'modified' => '2016-11-01 18:21:49',
            ],
            [
                'id' => '27',
                'model' => '4000',
                'description' => 'sit amet cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi',
                'price' => '33.88',
                'created' => '2014-11-28 15:11:49',
                'modified' => '2015-10-04 11:59:41',
            ],
            [
                'id' => '28',
                'model' => 'Excel',
                'description' => 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra',
                'price' => '47.05',
                'created' => '2015-08-07 13:24:31',
                'modified' => '2015-10-03 22:48:35',
            ],
            [
                'id' => '29',
                'model' => 'F250',
                'description' => 'posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam',
                'price' => '78.17',
                'created' => '2014-11-25 13:45:08',
                'modified' => '2017-03-08 06:47:50',
            ],
            [
                'id' => '30',
                'model' => 'Suburban 2500',
                'description' => 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit',
                'price' => '123.41',
                'created' => '2015-12-15 02:01:52',
                'modified' => '2016-03-16 12:24:14',
            ],
            [
                'id' => '31',
                'model' => '240SX',
                'description' => 'orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est donec odio justo sollicitudin ut',
                'price' => '159.96',
                'created' => '2014-07-31 02:57:52',
                'modified' => '2017-01-17 23:26:35',
            ],
            [
                'id' => '32',
                'model' => 'Tempo',
                'description' => 'enim leo rhoncus sed vestibulum sit amet cursus id turpis integer',
                'price' => '147.50',
                'created' => '2015-09-19 22:09:21',
                'modified' => '2016-04-04 21:01:30',
            ],
            [
                'id' => '33',
                'model' => 'E-Class',
                'description' => 'hac habitasse platea dictumst maecenas ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut',
                'price' => '60.27',
                'created' => '2015-02-18 08:11:06',
                'modified' => '2017-06-21 02:36:05',
            ],
            [
                'id' => '34',
                'model' => 'Grand Vitara',
                'description' => 'maecenas pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in',
                'price' => '79.48',
                'created' => '2015-09-01 01:43:03',
                'modified' => '2016-04-19 21:00:46',
            ],
            [
                'id' => '35',
                'model' => '9-5',
                'description' => 'purus aliquet at feugiat non pretium quis lectus suspendisse potenti in',
                'price' => '83.91',
                'created' => '2015-09-22 13:56:02',
                'modified' => '2017-02-04 06:36:38',
            ],
            [
                'id' => '36',
                'model' => 'Town Car',
                'description' => 'pede justo eu massa donec dapibus duis at velit eu est congue',
                'price' => '125.14',
                'created' => '2015-05-11 15:53:40',
                'modified' => '2016-06-11 13:35:28',
            ],
            [
                'id' => '37',
                'model' => 'Fusion',
                'description' => 'felis sed lacus morbi sem mauris laoreet ut rhoncus aliquet pulvinar sed nisl nunc rhoncus',
                'price' => '32.38',
                'created' => '2015-05-22 08:34:39',
                'modified' => '2015-07-15 04:43:53',
            ],
            [
                'id' => '38',
                'model' => 'Escalade EXT',
                'description' => 'duis ac nibh fusce lacus purus aliquet at feugiat non pretium quis',
                'price' => '171.99',
                'created' => '2015-11-02 06:02:20',
                'modified' => '2016-05-14 16:04:02',
            ],
            [
                'id' => '39',
                'model' => 'S70',
                'description' => 'lobortis convallis tortor risus dapibus augue vel accumsan tellus nisi eu orci mauris lacinia sapien quis libero nullam sit',
                'price' => '75.01',
                'created' => '2014-08-23 03:07:52',
                'modified' => '2016-03-03 02:35:19',
            ],
            [
                'id' => '40',
                'model' => 'Navajo',
                'description' => 'eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula consequat morbi a',
                'price' => '135.86',
                'created' => '2015-12-11 16:34:23',
                'modified' => '2016-05-08 07:30:20',
            ],
            [
                'id' => '41',
                'model' => 'Intrepid',
                'description' => 'potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus',
                'price' => '130.38',
                'created' => '2015-02-02 20:59:33',
                'modified' => '2017-01-07 13:31:25',
            ],
            [
                'id' => '42',
                'model' => '350Z',
                'description' => 'nulla suscipit ligula in lacus curabitur at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque',
                'price' => '97.78',
                'created' => '2015-11-19 16:20:13',
                'modified' => '2016-02-27 14:48:57',
            ],
            [
                'id' => '43',
                'model' => 'Impreza',
                'description' => 'pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus',
                'price' => '104.25',
                'created' => '2015-05-18 19:22:08',
                'modified' => '2015-11-25 23:20:52',
            ],
            [
                'id' => '45',
                'model' => 'Silverado 1500',
                'description' => 'mi integer ac neque duis bibendum morbi non quam nec dui luctus rutrum',
                'price' => '122.16',
                'created' => '2014-10-31 02:17:29',
                'modified' => '2016-03-26 23:11:17',
            ],
            [
                'id' => '46',
                'model' => '2500 Club Coupe',
                'description' => 'ut massa quis augue luctus tincidunt nulla mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh in hac',
                'price' => '21.62',
                'created' => '2015-04-04 17:14:34',
                'modified' => '2016-09-29 00:42:38',
            ],
            [
                'id' => '47',
                'model' => 'MKZ',
                'description' => 'vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla elit ac nulla',
                'price' => '115.21',
                'created' => '2015-07-05 19:03:47',
                'modified' => '2017-02-16 02:16:34',
            ],
            [
                'id' => '48',
                'model' => 'MGB',
                'description' => 'nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla ac enim in tempor',
                'price' => '195.17',
                'created' => '2015-07-16 09:31:41',
                'modified' => '2017-05-27 09:49:30',
            ],
            [
                'id' => '49',
                'model' => 'Taurus',
                'description' => 'eu tincidunt in leo maecenas pulvinar lobortis est phasellus sit',
                'price' => '40.66',
                'created' => '2015-03-14 21:14:02',
                'modified' => '2015-12-22 15:33:40',
            ],
            [
                'id' => '50',
                'model' => 'Ram 3500 Club',
                'description' => 'ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere',
                'price' => '102.17',
                'created' => '2016-02-15 00:08:06',
                'modified' => '2016-01-23 10:51:32',
            ],
            [
                'id' => '51',
                'model' => 'Villager',
                'description' => 'mauris eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies',
                'price' => '21.53',
                'created' => '2016-01-24 17:47:20',
                'modified' => '2015-12-05 18:21:07',
            ],
            [
                'id' => '52',
                'model' => 'Durango',
                'description' => 'nisi at nibh in hac habitasse platea dictumst aliquam augue quam sollicitudin vitae consectetuer eget rutrum',
                'price' => '196.53',
                'created' => '2014-12-08 01:12:22',
                'modified' => '2016-12-29 18:24:32',
            ],
            [
                'id' => '53',
                'model' => 'Cherokee',
                'description' => 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in',
                'price' => '29.98',
                'created' => '2014-12-18 16:28:19',
                'modified' => '2016-01-12 02:32:57',
            ],
            [
                'id' => '54',
                'model' => 'Wrangler',
                'description' => 'sapien placerat ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros',
                'price' => '89.97',
                'created' => '2015-03-22 14:09:37',
                'modified' => '2016-08-19 13:39:38',
            ],
            [
                'id' => '55',
                'model' => 'Matrix',
                'description' => 'bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem',
                'price' => '36.88',
                'created' => '2015-10-14 05:37:12',
                'modified' => '2016-09-23 02:47:57',
            ],
            [
                'id' => '56',
                'model' => 'Escalade',
                'description' => 'turpis a pede posuere nonummy integer non velit donec diam neque',
                'price' => '41.29',
                'created' => '2014-08-30 09:50:59',
                'modified' => '2016-02-06 18:55:48',
            ],
            [
                'id' => '57',
                'model' => 'STS',
                'description' => 'nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim',
                'price' => '69.85',
                'created' => '2014-08-06 20:47:11',
                'modified' => '2016-10-05 00:04:34',
            ],
            [
                'id' => '58',
                'model' => 'Savana 2500',
                'description' => 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus',
                'price' => '31.75',
                'created' => '2014-08-31 07:40:13',
                'modified' => '2016-07-09 01:24:01',
            ],
            [
                'id' => '59',
                'model' => 'Corrado',
                'description' => 'cras pellentesque volutpat dui maecenas tristique est et tempus semper est quam',
                'price' => '45.72',
                'created' => '2016-01-12 20:16:18',
                'modified' => '2016-11-22 10:27:47',
            ],
            [
                'id' => '60',
                'model' => 'Cabriolet',
                'description' => 'ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae nulla dapibus dolor vel est',
                'price' => '127.82',
                'created' => '2014-07-09 19:37:37',
                'modified' => '2017-04-25 22:51:51',
            ],
            [
                'id' => '61',
                'model' => 'Diamante',
                'description' => 'ut odio cras mi pede malesuada in imperdiet et commodo vulputate justo in',
                'price' => '30.78',
                'created' => '2015-12-17 21:25:56',
                'modified' => '2016-05-04 10:48:15',
            ],
            [
                'id' => '62',
                'model' => 'Grand Prix',
                'description' => 'donec vitae nisi nam ultrices libero non mattis pulvinar nulla pede ullamcorper augue a suscipit nulla',
                'price' => '39.87',
                'created' => '2015-02-25 13:26:26',
                'modified' => '2016-05-21 13:31:53',
            ],
            [
                'id' => '63',
                'model' => 'Monterey',
                'description' => 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et',
                'price' => '95.26',
                'created' => '2015-08-11 03:58:51',
                'modified' => '2016-04-15 03:06:07',
            ],
            [
                'id' => '64',
                'model' => 'Interceptor',
                'description' => 'in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra diam vitae quam suspendisse potenti nullam',
                'price' => '28.78',
                'created' => '2015-02-26 08:12:56',
                'modified' => '2016-04-07 19:17:41',
            ],
            [
                'id' => '65',
                'model' => 'Express 3500',
                'description' => 'phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu mi nulla',
                'price' => '137.97',
                'created' => '2014-10-04 13:43:30',
                'modified' => '2016-05-03 15:16:38',
            ],
            [
                'id' => '66',
                'model' => 'GX',
                'description' => 'id ornare imperdiet sapien urna pretium nisl ut volutpat sapien arcu sed augue aliquam erat volutpat in',
                'price' => '65.34',
                'created' => '2014-10-05 22:29:20',
                'modified' => '2016-05-18 16:26:43',
            ],
            [
                'id' => '67',
                'model' => 'Park Avenue',
                'description' => 'sit amet consectetuer adipiscing elit proin risus praesent lectus vestibulum quam sapien varius ut blandit',
                'price' => '86.87',
                'created' => '2014-10-12 19:45:03',
                'modified' => '2017-05-01 02:27:15',
            ],
            [
                'id' => '68',
                'model' => 'NSX',
                'description' => 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque',
                'price' => '138.41',
                'created' => '2015-07-23 22:25:49',
                'modified' => '2016-07-12 14:14:34',
            ],
            [
                'id' => '69',
                'model' => '1 Series',
                'description' => 'nulla eget eros elementum pellentesque quisque porta volutpat erat quisque erat',
                'price' => '37.59',
                'created' => '2014-12-14 15:33:27',
                'modified' => '2017-01-21 05:10:12',
            ],
            [
                'id' => '70',
                'model' => 'Galant',
                'description' => 'quam sollicitudin vitae consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent',
                'price' => '166.49',
                'created' => '2015-07-07 07:10:20',
                'modified' => '2016-08-15 15:16:51',
            ],
            [
                'id' => '71',
                'model' => 'Z4',
                'description' => 'vel augue vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id nisl',
                'price' => '161.86',
                'created' => '2015-04-19 03:50:50',
                'modified' => '2016-01-02 14:02:34',
            ],
            [
                'id' => '72',
                'model' => 'Thunderbird',
                'description' => 'volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim',
                'price' => '100.37',
                'created' => '2015-08-11 21:34:22',
                'modified' => '2016-09-09 07:18:28',
            ],
            [
                'id' => '73',
                'model' => 'Suburban 2500',
                'description' => 'turpis sed ante vivamus tortor duis mattis egestas metus aenean',
                'price' => '59.39',
                'created' => '2015-01-02 08:48:11',
                'modified' => '2016-11-01 02:27:33',
            ],
            [
                'id' => '74',
                'model' => 'C-Class',
                'description' => 'pulvinar lobortis est phasellus sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum proin eu',
                'price' => '38.90',
                'created' => '2015-01-03 01:28:00',
                'modified' => '2016-10-27 21:34:43',
            ],
            [
                'id' => '75',
                'model' => 'Prius Plug-in Hybrid',
                'description' => 'dui nec nisi volutpat eleifend donec ut dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus',
                'price' => '197.48',
                'created' => '2015-03-02 20:14:36',
                'modified' => '2017-04-02 00:54:04',
            ],
            [
                'id' => '76',
                'model' => 'IS',
                'description' => 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat',
                'price' => '124.32',
                'created' => '2015-09-10 01:14:39',
                'modified' => '2015-12-02 00:04:29',
            ],
            [
                'id' => '77',
                'model' => 'Exige',
                'description' => 'pretium nisl ut volutpat sapien arcu sed augue aliquam erat',
                'price' => '149.01',
                'created' => '2014-07-27 13:38:28',
                'modified' => '2016-08-13 11:54:04',
            ],
            [
                'id' => '78',
                'model' => 'Grand Prix',
                'description' => 'nam nulla integer pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor',
                'price' => '159.60',
                'created' => '2015-11-10 10:17:16',
                'modified' => '2015-09-18 23:39:15',
            ],
            [
                'id' => '79',
                'model' => 'Flex',
                'description' => 'pede venenatis non sodales sed tincidunt eu felis fusce posuere felis sed lacus morbi sem',
                'price' => '35.22',
                'created' => '2014-09-22 12:45:50',
                'modified' => '2017-02-04 22:16:20',
            ],
            [
                'id' => '80',
                'model' => 'Park Avenue',
                'description' => 'auctor gravida sem praesent id massa id nisl venenatis lacinia aenean sit amet justo morbi ut',
                'price' => '193.16',
                'created' => '2015-11-22 02:24:24',
                'modified' => '2015-08-06 19:35:29',
            ],
            [
                'id' => '81',
                'model' => 'Solara',
                'description' => 'eget massa tempor convallis nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque id justo sit',
                'price' => '101.94',
                'created' => '2015-06-22 20:41:21',
                'modified' => '2017-03-02 19:09:49',
            ],
            [
                'id' => '82',
                'model' => '200',
                'description' => 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae',
                'price' => '61.76',
                'created' => '2015-06-24 16:00:30',
                'modified' => '2016-08-17 02:04:01',
            ],
            [
                'id' => '83',
                'model' => 'Solstice',
                'description' => 'mauris non ligula pellentesque ultrices phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at',
                'price' => '26.47',
                'created' => '2015-05-10 15:54:43',
                'modified' => '2017-05-29 15:45:39',
            ],
            [
                'id' => '84',
                'model' => 'S-Class',
                'description' => 'nisi venenatis tristique fusce congue diam id ornare imperdiet sapien urna pretium nisl ut volutpat',
                'price' => '78.08',
                'created' => '2015-01-10 06:01:25',
                'modified' => '2017-05-14 00:58:03',
            ],
            [
                'id' => '85',
                'model' => 'Sportage',
                'description' => 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non',
                'price' => '107.66',
                'created' => '2015-01-26 18:30:50',
                'modified' => '2016-06-30 06:15:00',
            ],
            [
                'id' => '86',
                'model' => 'E-Class',
                'description' => 'tristique fusce congue diam id ornare imperdiet sapien urna pretium',
                'price' => '172.09',
                'created' => '2016-02-03 12:07:39',
                'modified' => '2016-10-26 12:25:49',
            ],
            [
                'id' => '87',
                'model' => 'GTO',
                'description' => 'ante nulla justo aliquam quis turpis eget elit sodales scelerisque mauris sit amet eros suspendisse accumsan',
                'price' => '115.62',
                'created' => '2014-12-01 04:41:20',
                'modified' => '2017-04-13 15:10:11',
            ],
            [
                'id' => '88',
                'model' => 'xB',
                'description' => 'a feugiat et eros vestibulum ac est lacinia nisi venenatis tristique',
                'price' => '72.73',
                'created' => '2015-01-05 12:19:54',
                'modified' => '2016-09-27 01:40:48',
            ],
            [
                'id' => '89',
                'model' => 'Club Wagon',
                'description' => 'lectus in est risus auctor sed tristique in tempus sit amet sem fusce consequat nulla nisl nunc nisl duis',
                'price' => '57.43',
                'created' => '2016-01-20 07:58:02',
                'modified' => '2015-10-21 09:55:04',
            ],
            [
                'id' => '90',
                'model' => 'G37',
                'description' => 'sapien iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget',
                'price' => '118.67',
                'created' => '2016-02-02 08:22:45',
                'modified' => '2017-06-23 23:31:07',
            ],
            [
                'id' => '91',
                'model' => 'Quattroporte',
                'description' => 'faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis consequat dui nec nisi',
                'price' => '154.27',
                'created' => '2015-12-11 23:21:37',
                'modified' => '2016-09-03 14:14:31',
            ],
            [
                'id' => '92',
                'model' => 'Sportvan G20',
                'description' => 'lobortis sapien sapien non mi integer ac neque duis bibendum morbi non quam nec dui luctus',
                'price' => '185.59',
                'created' => '2015-03-28 01:06:33',
                'modified' => '2015-07-14 21:38:41',
            ],
            [
                'id' => '93',
                'model' => 'Sportvan G30',
                'description' => 'id ligula suspendisse ornare consequat lectus in est risus auctor sed tristique in',
                'price' => '163.75',
                'created' => '2014-08-13 22:44:35',
                'modified' => '2016-06-09 19:35:45',
            ],
            [
                'id' => '94',
                'model' => 'tC',
                'description' => 'sapien a libero nam dui proin leo odio porttitor id consequat in consequat',
                'price' => '95.80',
                'created' => '2015-05-31 12:43:59',
                'modified' => '2016-02-19 09:53:14',
            ],
            [
                'id' => '95',
                'model' => 'Golf',
                'description' => 'id nisl venenatis lacinia aenean sit amet justo morbi ut',
                'price' => '58.31',
                'created' => '2014-11-28 20:37:12',
                'modified' => '2017-02-03 23:04:46',
            ],
            [
                'id' => '96',
                'model' => 'RX',
                'description' => 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae duis faucibus accumsan odio curabitur convallis duis',
                'price' => '63.06',
                'created' => '2014-10-27 09:20:37',
                'modified' => '2017-03-30 14:27:00',
            ],
            [
                'id' => '97',
                'model' => 'Intrepid',
                'description' => 'in imperdiet et commodo vulputate justo in blandit ultrices enim lorem ipsum',
                'price' => '165.93',
                'created' => '2015-05-03 10:36:32',
                'modified' => '2016-07-16 14:21:37',
            ],
            [
                'id' => '98',
                'model' => 'Grand Cherokee',
                'description' => 'donec pharetra magna vestibulum aliquet ultrices erat tortor sollicitudin mi sit amet lobortis sapien sapien non mi',
                'price' => '120.31',
                'created' => '2015-04-25 04:45:51',
                'modified' => '2015-09-06 03:19:52',
            ],
            [
                'id' => '99',
                'model' => 'X-90',
                'description' => 'est et tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus',
                'price' => '121.13',
                'created' => '2015-12-12 23:55:46',
                'modified' => '2017-02-22 15:42:32',
            ],
            [
                'id' => '100',
                'model' => 'I',
                'description' => 'iaculis congue vivamus metus arcu adipiscing molestie hendrerit at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis',
                'price' => '108.60',
                'created' => '2015-01-29 06:03:18',
                'modified' => '2016-01-24 13:23:46',
            ],
        ];

        $table = $this->table('turbines');
        $table->insert($data)->save();
    }
}
